import React, { useState } from 'react';

const tabs = [
  "FAVORITES", "FINANCE", "ORDERS", "RETURNS", "ITEM DATA", "PERFORMANCE", "ALL REPORTS"
];

const reportData = {
  FAVORITES: [],
  FINANCE: [
    {
      title: "Financial Reconciliation",
      usage: "View Stripe transfers per order line and payouts in a given time period."
    },
    {
      title: "Partner Sales and Tax",
      usage: "View taxable sales details by state."
    }
  ],
  ORDERS: [
    {
      title: "Orders",
      usage: "View SKU level order data with requested ship date, delivery date, unit price and RedCard discount (if any)."
    }
  ],
  RETURNS: [
    {
      title: "Returns",
      usage: "View SKU level return data with guest return reason, qty, dispositions, locations, tracking, BOL, license plate (if any) and more."
    }
  ],
  "ITEM DATA": [
    { title: "Item Errors", usage: "See rejected Items by Critical and Non-Critical errors." },
    { title: "Allowed Item Types", usage: "View every allowed item type with description, referral rate, subtype and brand restrictions (if any)." },
    { title: "Attributes & Values", usage: "View required & recommended attributes with allowed values for each." },
    { title: "Items with Logistics Errors", usage: "See items with errors on return policy, shipping, or exclusion values." },
  ],
  PERFORMANCE: [
    { title: "Order Defect Rate", usage: "Look into late deliveries, cancelations, guest contact and returns that negatively affected your ODR." },
    { title: "Sales Metrics", usage: "See item level GMV, conversion rate or return rate for all units sold in a given time period." },
    { title: "Content Score", usage: "Bi-weekly evaluation of content quality and accuracy for all published VAPs and SAs." },
  ],
  "ALL REPORTS": []
};

export default function ReportsPage() {
  const [activeTab, setActiveTab] = useState("ALL REPORTS");

  const getReports = () => {
    if (activeTab === "ALL REPORTS") {
      // Merge all reports for all tabs except Favorites and All Reports
      return Object.entries(reportData)
        .filter(([key]) => key !== "FAVORITES" && key !== "ALL REPORTS")
        .flatMap(([_, reports]) => reports);
    }
    return reportData[activeTab] || [];
  };

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-2xl font-bold">All Reports</h1>

      {/* Subsection: Reports generated by me */}
      <div>
        <h2 className="font-semibold text-lg">Reports Generated by Me</h2>
        <p className="text-gray-500">No reports generated yet.</p>
      </div>

      {/* Report Templates Title */}
      <div className="pt-4">
        <h2 className="font-semibold text-lg">Report Templates</h2>
      </div>

      {/* Tabs */}
      <div className="flex space-x-6 border-b mt-2 text-sm">
        {tabs.map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`pb-2 ${activeTab === tab ? "border-b-2 border-blue-600 text-blue-600 font-semibold" : "text-gray-700"}`}
          >
            {tab}
          </button>
        ))}
      </div>

      {/* Report Table */}
      <div className="mt-4 border-t">
        {getReports().length === 0 ? (
          <p className="text-sm text-gray-600 mt-4">No {activeTab.toLowerCase()} reports available.</p>
        ) : (
          <div className="divide-y">
            {getReports().map((report, index) => (
              <div key={index} className="flex justify-between items-center px-2 py-4">
                <div className="flex items-start space-x-4">
                  <button className="text-blue-600 text-xl">&#9825;</button>
                  <div>
                    <div className="font-semibold">{report.title}</div>
                    <div className="text-sm text-gray-600">{report.usage}</div>
                  </div>
                </div>
                <button className="border border-blue-600 text-blue-600 px-4 py-1 rounded hover:bg-blue-50 text-sm">GENERATE REPORT</button>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
